### ISSUE TITLE
An Issue but not important

### ISSUE THREAD

**Issue by ghost** [gmestanley/DNH-V#2]
Hello,gmestanley.Maybe it isn't important.I found some of games’ Chinese translate version does not run well on all Dnh based on dnh_woo.I don't know why.But there are also some are working and display Chinese normally.
<img width="601" alt="1" src="https://user-images.githubusercontent.com/121996277/211960479-ff10934f-20a5-4498-a7ef-0db789637bd0.PNG">
<img width="601" alt="2" src="https://user-images.githubusercontent.com/121996277/211960501-59266b8a-8bf1-4c08-949c-401f4daa0744.PNG">
<img width="601" alt="3" src="https://user-images.githubusercontent.com/121996277/211960517-f4e43e58-618f-4d5d-9b8f-0648d06c462d.PNG">
<img width="601" alt="4" src="https://user-images.githubusercontent.com/121996277/211960528-dc022bfc-1c75-44c1-972f-79ff96dcef89.PNG">
<img width="601" alt="5" src="https://user-images.githubusercontent.com/121996277/211960537-56993863-3bad-4882-8064-d07e2346b63a.PNG">
<img width="601" alt="6" src="https://user-images.githubusercontent.com/121996277/211960548-0c085da8-ec04-4ce6-8bdb-248ab08dd09f.PNG">
<img width="601" alt="7" src="https://user-images.githubusercontent.com/121996277/211960563-b0f7d52d-0677-4dc5-a1e8-ba66f7a37bcf.PNG">
<img width="601" alt="8" src="https://user-images.githubusercontent.com/121996277/211960583-9558764f-6441-417b-a235-6c6650410d3b.PNG">
<img width="601" alt="9" src="https://user-images.githubusercontent.com/121996277/211960601-7d2755fb-a09e-4419-91bd-b0e3b4fd805b.PNG">
<img width="601" alt="10" src="https://user-images.githubusercontent.com/121996277/211960615-8d55e910-9ea3-4912-955b-0e9b95f6b96b.PNG">

**Comment by gmestanley** [comment]
Hello!
The reason why some Chinese text works and some doesn't is because the one that works is in the form of images. The one that doesn't work is just text, which is what is appearing as corrupted here.
I investigated this and this is most definitely an encoding issue. Text that's supposed to be in GB2312 is being parsed as Shift-JIS; it would be recommended for the patch to re-encode the text in UTF-16 to work on default DNH, since that encoding is the only one it supports that provides Chinese characters. DNH-V will probably include support for GB2312 if needed.
Thank you for the comment! It was a delight to find the issue's cause.
