### ISSUE TITLE
Is the source code based on danmakufu ph3.5 nf4?

### ISSUE THREAD

**Issue by ghost** [gmestanley/DNH-V#3]
Hello,gmestanley,Is the source code based on danmakufu ph3.5 nf4? Why I can't run games in the DNH-V after I trying to build from  source?Am I have some wrongs on build?
[bin_th_dnh-v_test1.zip](https://github.com/gmestanley/DNH-V/files/10474247/bin_th_dnh-v_test1.zip)

**Comment by ghost** [comment]
Now I have some wrongs about that account,so I must change to other account now.

**Comment by gmestanley** [comment]
Hello, sorry for the late answer, I've been busy. Yes, the source code is based on ph3.5 nf4.
Do you mean that you literally can't execute games on DNH-V or that it didn't compile? I ask because I can't see any issue with the (main) code and I'm pretty sure it compiles fine on my computer.
The latter depends on what exactly did you build: did you compile the whole solution or the DnhExecutor project? That one is the core part of DNH, the executable, which is what you need and that, again, has no issue in its code.
If it's the former, please provide what exactly is happening, like if there's a message box with an error appearing after running a game or the engine itself, if the engine doesn't run or if it crashes after running a game.
